# Generated by Django 6.0.3 on 2026-03-26 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_2fa_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_2fa_enabled",
        ),
        migrations.RemoveField(
            model_name="user",
            name="two_factor_secret",
        ),
        migrations.DeleteModel(
            name="TwoFactorAuth",
        ),
    ]
