# Generated by Django 6.0.3 on 2026-04-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_loginattempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="unique_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=20, null=True, unique=True
            ),
        ),
    ]
