# Generated by Django 6.0.3 on 2026-04-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_add_unique_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("patient", "Patient"),
                    ("clinician", "Clinician / Doctor"),
                    ("hcc_staff", "PHC Staff"),
                    ("hcc_admin", "PHC Admin"),
                    ("fhc_staff", "FMC Staff"),
                    ("fhc_admin", "FMC Admin"),
                    ("sth_staff", "State Hospital Staff"),
                    ("sth_admin", "State Hospital Admin"),
                    ("stth_staff", "State Teaching Hospital Staff"),
                    ("stth_admin", "State Teaching Hospital Admin"),
                    ("fth_staff", "Federal Teaching Hospital Staff"),
                    ("fth_admin", "Federal Teaching Hospital Admin"),
                    ("admin", "Platform Admin"),
                ],
                db_index=True,
                default="patient",
                max_length=20,
            ),
        ),
    ]
