# Generated by Django 6.0.3 on 2026-04-11 09:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centers", "0002_alter_federalhealthcenter_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Consultation"),
                            ("followup", "Follow-up Visit"),
                            ("routine", "Routine Check"),
                            ("urgent", "Urgent Care"),
                        ],
                        default="routine",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("vital_signs", models.JSONField(blank=True, null=True)),
                ("diagnosis", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation_notes",
                        to="centers.patientcase",
                    ),
                ),
                (
                    "clinician",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultation_notes",
                        to="centers.clinicianprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TreatmentPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("medications", models.JSONField(blank=True, null=True)),
                ("lifestyle", models.JSONField(blank=True, null=True)),
                ("follow_up_days", models.PositiveSmallIntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatment_plans",
                        to="centers.patientcase",
                    ),
                ),
                (
                    "clinician",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treatment_plans",
                        to="centers.clinicianprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
