# Generated by Django 6.0.3 on 2026-04-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centers", "0004_prescription"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicianprofile",
            name="downstream_expertise",
            field=models.JSONField(
                default=list,
                help_text="List of downstream diseases this clinician can manage",
            ),
        ),
        migrations.AddField(
            model_name="clinicianprofile",
            name="onboarded",
            field=models.BooleanField(
                default=False, help_text="Whether clinician has completed onboarding"
            ),
        ),
        migrations.AddField(
            model_name="clinicianprofile",
            name="onboarded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="clinicianprofile",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("general_practice", "General Practice"),
                    ("family_medicine", "Family Medicine"),
                    ("internal_medicine", "Internal Medicine"),
                    ("obstetrics_gynae", "Obstetrics & Gynaecology"),
                    (
                        "reproductive_endocrinology",
                        "Reproductive Endocrinology & Infertility",
                    ),
                    ("gynecologic_oncology", "Gynecologic Oncology"),
                    ("endocrinology", "Endocrinology"),
                    ("diabetology", "Diabetology"),
                    ("cardiology", "Cardiology"),
                    ("hypertension", "Hypertension & Vascular Medicine"),
                    ("obesity_medicine", "Obesity Medicine"),
                    ("hepatology", "Hepatology / Gastroenterology"),
                    ("sleep_medicine", "Sleep Medicine"),
                    ("pulmonology", "Pulmonology"),
                    ("maternal_fetal_medicine", "Maternal-Fetal Medicine"),
                    ("adolescent_medicine", "Adolescent Medicine"),
                    ("psychiatry", "Psychiatry"),
                    ("clinical_psychology", "Clinical Psychology"),
                    ("dermatology", "Dermatology"),
                    ("nutrition", "Nutrition & Dietetics"),
                    ("community_health", "Community Health"),
                    ("public_health", "Public Health & Epidemiology"),
                    ("midwifery", "Midwifery"),
                    ("nursing", "Nursing"),
                    ("other", "Other"),
                ],
                default="general_practice",
                max_length=40,
            ),
        ),
    ]
