# Generated by Django 6.0.3 on 2026-04-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centers", "0005_clinicianprofile_downstream_expertise_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clinicianprofile",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("general_practice", "General Practice"),
                    ("family_medicine", "Family Medicine"),
                    ("internal_medicine", "Internal Medicine"),
                    ("preventive_medicine", "Preventive Medicine"),
                    ("obstetrics_gynae", "Obstetrics & Gynaecology"),
                    (
                        "reproductive_endocrinology",
                        "Reproductive Endocrinology & Infertility",
                    ),
                    ("gynecologic_oncology", "Gynecologic Oncology"),
                    ("endocrinology", "Endocrinology"),
                    ("diabetology", "Diabetology"),
                    ("cardiology", "Cardiology"),
                    ("hypertension", "Hypertension & Vascular Medicine"),
                    ("obesity_medicine", "Obesity Medicine"),
                    ("behavioral_medicine", "Behavioral Medicine"),
                    ("gastroenterology", "Gastroenterology"),
                    ("hepatology", "Hepatology"),
                    ("sleep_medicine", "Sleep Medicine"),
                    ("pulmonology", "Pulmonology"),
                    ("ent", "ENT"),
                    ("maternal_fetal_medicine", "Maternal-Fetal Medicine"),
                    ("adolescent_medicine", "Adolescent Medicine"),
                    ("psychiatry", "Psychiatry"),
                    ("clinical_psychology", "Clinical Psychology"),
                    ("community_mental_health", "Community Mental Health"),
                    ("dermatology", "Dermatology"),
                    ("nutrition", "Nutrition & Dietetics"),
                    ("community_health", "Community Health"),
                    ("public_health", "Public Health & Epidemiology"),
                    ("midwifery", "Midwifery"),
                    ("nursing", "Nursing"),
                    ("other", "Other"),
                ],
                default="general_practice",
                max_length=40,
            ),
        ),
    ]
