# Generated by Django 6.0.3 on 2026-04-17 17:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centers", "0006_alter_clinicianprofile_specialization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="healthcarecenter",
            name="escalates_to",
        ),
        migrations.CreateModel(
            name="FederalTeachingHospital",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. FTH-001", max_length=20, unique=True
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("state", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "zone",
                    models.CharField(
                        blank=True, help_text="Geopolitical zone", max_length=100
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending Verification"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_user",
                    models.OneToOneField(
                        blank=True,
                        limit_choices_to={"role": "fth_admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_federal_teaching",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Federal Teaching Hospital",
                "verbose_name_plural": "Federal Teaching Hospitals",
                "ordering": ["state", "name"],
            },
        ),
        migrations.AddField(
            model_name="federalhealthcenter",
            name="escalates_to_federal_teaching",
            field=models.ForeignKey(
                blank=True,
                help_text="Federal Teaching Hospital this FMC escalates critical cases to when needed.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referring_fmcs",
                to="centers.federalteachinghospital",
            ),
        ),
        migrations.CreateModel(
            name="StateHospital",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. STH-LGS-001", max_length=20, unique=True
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("state", models.CharField(blank=True, db_index=True, max_length=100)),
                ("lga", models.CharField(blank=True, max_length=100)),
                (
                    "zone",
                    models.CharField(
                        blank=True, help_text="Geopolitical zone", max_length=100
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending Verification"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_user",
                    models.OneToOneField(
                        blank=True,
                        limit_choices_to={"role": "sth_admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_state_hospital",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "State General Hospital",
                "verbose_name_plural": "State General Hospitals",
                "ordering": ["state", "name"],
            },
        ),
        migrations.AddField(
            model_name="healthcarecenter",
            name="escalates_to_state_hospital",
            field=models.ForeignKey(
                blank=True,
                help_text="The State General Hospital this PHC escalates Moderate/Severe patients to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referring_phcs",
                to="centers.statehospital",
            ),
        ),
        migrations.CreateModel(
            name="StateTeachingHospital",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. STTH-LGS-001", max_length=20, unique=True
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("state", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "zone",
                    models.CharField(
                        blank=True, help_text="Geopolitical zone", max_length=100
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending Verification"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_user",
                    models.OneToOneField(
                        blank=True,
                        limit_choices_to={"role": "stth_admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_state_teaching",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "escalates_to_federal_teaching",
                    models.ForeignKey(
                        blank=True,
                        help_text="Federal Teaching Hospital this teaching hospital escalates critical cases to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referring_state_teaching_hospitals",
                        to="centers.federalteachinghospital",
                    ),
                ),
                (
                    "escalates_to_fmc",
                    models.ForeignKey(
                        blank=True,
                        help_text="FMC this teaching hospital escalates to for very severe cases.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referring_state_teaching_hospitals",
                        to="centers.federalhealthcenter",
                    ),
                ),
            ],
            options={
                "verbose_name": "State Teaching Hospital",
                "verbose_name_plural": "State Teaching Hospitals",
                "ordering": ["state", "name"],
            },
        ),
        migrations.AddField(
            model_name="statehospital",
            name="escalates_to_state_teaching",
            field=models.ForeignKey(
                blank=True,
                help_text="State Teaching Hospital this hospital escalates to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referring_state_hospitals",
                to="centers.stateteachinghospital",
            ),
        ),
        migrations.AddField(
            model_name="federalhealthcenter",
            name="escalates_to_state_teaching",
            field=models.ForeignKey(
                blank=True,
                help_text="State Teaching Hospital this FMC escalates Very Severe cases to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referring_fmcs",
                to="centers.stateteachinghospital",
            ),
        ),
    ]
