# Generated by Django 6.0.3 on 2026-04-19 19:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centers", "0007_add_new_hospital_tiers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. CLN-001", max_length=20, unique=True
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("state", models.CharField(blank=True, db_index=True, max_length=100)),
                ("lga", models.CharField(blank=True, max_length=100)),
                (
                    "zone",
                    models.CharField(
                        blank=True, help_text="Geopolitical zone", max_length=100
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending Verification"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_user",
                    models.OneToOneField(
                        blank=True,
                        limit_choices_to={"role": "clinic_admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_clinic",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Clinic",
                "verbose_name_plural": "Clinics",
                "ordering": ["state", "name"],
            },
        ),
        migrations.CreateModel(
            name="HealthInsuranceOrganization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. HMO-001", max_length=20, unique=True
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("state", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "zone",
                    models.CharField(
                        blank=True, help_text="Geopolitical zone", max_length=100
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending Verification"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("license_number", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_user",
                    models.OneToOneField(
                        blank=True,
                        limit_choices_to={"role": "hmo_admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_hmo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Insurance Organization (HMO)",
                "verbose_name_plural": "Health Insurance Organizations (HMOs)",
                "ordering": ["state", "name"],
            },
        ),
        migrations.CreateModel(
            name="PrivateHospital",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. PVT-001", max_length=20, unique=True
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("state", models.CharField(blank=True, db_index=True, max_length=100)),
                ("lga", models.CharField(blank=True, max_length=100)),
                (
                    "zone",
                    models.CharField(
                        blank=True, help_text="Geopolitical zone", max_length=100
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending Verification"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_user",
                    models.OneToOneField(
                        blank=True,
                        limit_choices_to={"role": "pvt_admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_private_hospital",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Private Hospital",
                "verbose_name_plural": "Private Hospitals",
                "ordering": ["state", "name"],
            },
        ),
        migrations.CreateModel(
            name="PrivateTeachingHospital",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. PTTH-001", max_length=20, unique=True
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("state", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "zone",
                    models.CharField(
                        blank=True, help_text="Geopolitical zone", max_length=100
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending Verification"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin_user",
                    models.OneToOneField(
                        blank=True,
                        limit_choices_to={"role": "ptth_admin"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_ptth",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Private Teaching Hospital",
                "verbose_name_plural": "Private Teaching Hospitals",
                "ordering": ["state", "name"],
            },
        ),
    ]
