# Generated by Django 6.0.3 on 2026-04-19 19:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("centers", "0008_clinic_healthinsuranceorganization_privatehospital_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-3 code", max_length=3, unique=True
                    ),
                ),
                (
                    "code_2",
                    models.CharField(
                        blank=True,
                        help_text="ISO 3166-1 alpha-2 code",
                        max_length=2,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="clinic",
            name="facility_type",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("insurance", "Health Insurance (HMO)"),
                ],
                default="private",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="federalhealthcenter",
            name="facility_type",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("insurance", "Health Insurance (HMO)"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="federalhealthcenter",
            name="lga",
            field=models.CharField(blank=True, max_length=100, verbose_name="LGA"),
        ),
        migrations.AddField(
            model_name="federalteachinghospital",
            name="facility_type",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("insurance", "Health Insurance (HMO)"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="federalteachinghospital",
            name="lga",
            field=models.CharField(blank=True, max_length=100, verbose_name="LGA"),
        ),
        migrations.AddField(
            model_name="healthcarecenter",
            name="facility_type",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("insurance", "Health Insurance (HMO)"),
                ],
                default="public",
                help_text="Classification: Public, Private, or Insurance",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="healthinsuranceorganization",
            name="facility_type",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("insurance", "Health Insurance (HMO)"),
                ],
                default="insurance",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="healthinsuranceorganization",
            name="lga",
            field=models.CharField(blank=True, max_length=100, verbose_name="LGA"),
        ),
        migrations.AddField(
            model_name="privatehospital",
            name="facility_type",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("insurance", "Health Insurance (HMO)"),
                ],
                default="private",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="privateteachinghospital",
            name="facility_type",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("insurance", "Health Insurance (HMO)"),
                ],
                default="private",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="privateteachinghospital",
            name="lga",
            field=models.CharField(blank=True, max_length=100, verbose_name="LGA"),
        ),
        migrations.AddField(
            model_name="statehospital",
            name="facility_type",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("insurance", "Health Insurance (HMO)"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="stateteachinghospital",
            name="facility_type",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("insurance", "Health Insurance (HMO)"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="stateteachinghospital",
            name="lga",
            field=models.CharField(blank=True, max_length=100, verbose_name="LGA"),
        ),
        migrations.AddField(
            model_name="clinic",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clinics",
                to="centers.country",
            ),
        ),
        migrations.AddField(
            model_name="federalhealthcenter",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="federal_health_centers",
                to="centers.country",
            ),
        ),
        migrations.AddField(
            model_name="federalteachinghospital",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="federal_teaching_hospitals",
                to="centers.country",
            ),
        ),
        migrations.AddField(
            model_name="healthcarecenter",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="health_centers",
                to="centers.country",
            ),
        ),
        migrations.AddField(
            model_name="healthinsuranceorganization",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="health_insurance_orgs",
                to="centers.country",
            ),
        ),
        migrations.AddField(
            model_name="privatehospital",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="private_hospitals",
                to="centers.country",
            ),
        ),
        migrations.AddField(
            model_name="privateteachinghospital",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="private_teaching_hospitals",
                to="centers.country",
            ),
        ),
        migrations.AddField(
            model_name="statehospital",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="state_hospitals",
                to="centers.country",
            ),
        ),
        migrations.AddField(
            model_name="stateteachinghospital",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="state_teaching_hospitals",
                to="centers.country",
            ),
        ),
    ]
