# Generated by Django 6.0.3 on 2026-04-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0002_onboardingprofile_lga_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="onboardingprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="onboardingprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
